# https://aka.ms/yaml
# https://aka.ms/hosted-agent-software
# https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting
# https://github.com/OpenImageIO/oiio/blob/master/INSTALL.md

jobs:
- job: 'vcpython27'

  strategy:
    matrix:
      vs2017-win2016:
        azure.vm_image: 'vs2017-win2016'

  variables:
    src.vcpython27: '$(Agent.BuildDirectory)/s'

  pool:
    vmImage: $(azure.vm_image)


  steps:


  # Create package
  - powershell: |
      cd $(src.vcpython27)
      choco pack
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Package

  # Install python27
  - powershell: |
      cd $(src.vcpython27)
      choco install -y vcpython27 -s "$pwd" -f
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Install

  # Uninstall python27
  - powershell: |
      choco uninstall -y vcpython27
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Uninstall

